workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

image: registry.eulix.xyz/collab/infra/public-service/maven:3.6.3-openjdk-11

stages:
  - license_check
  - license_fix
  - validate
  - docker
  - manifest
  - sign
  - codelint
  - cloc

include:
  - project: 'bp/ams-ci-template'
    ref: main
    file: '/sonarqube.yml'
  - project: 'bp/ams-ci-template'
    ref: main
    file: '/license.yml'
  - project: 'bp/ams-ci-template'
    ref: main
    file: '/container.yml'
  - project: 'bp/ams-ci-template'
    ref: main
    file: '/sign.yml'
  - project: 'bp/ams-ci-template'
    ref: main
    file: '/cloc.yml'

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  ENV_SONARQUBE_TYPE: maven
  ENV_LICENSE_TYPE: maven
  ENV_CONTAINER_NAME: eulixplatform-services
  LM_JAVA_VERSION: 11

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .m2/repository
    - .sonar/cache

validate:build:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - x86_64
  script:
    - mvn $MAVEN_CLI_OPTS test-compile

validate:test:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - x86_64
  script:
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
    - echo "The Jacoco Report URL：https://bp.pages.eulix.xyz/-/platform/eulixplatform-services/-/jobs/${CI_JOB_ID}/artifacts/target/site/jacoco/index.html"
  artifacts:
    paths:
      - target/site/jacoco/

validate:package:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - x86_64
  script:
    - mvn $MAVEN_CLI_OPTS package
    - wget https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64 -O /usr/bin/ossutil64 && chmod +x /usr/bin/ossutil64
    - ossutil64 -i $OSS_CI_EULIX_RES_ACCESS_ID -k $OSS_CI_EULIX_RES_ACCESS_KEY -e $OSS_CI_EULIX_RES_ENDPOINT cp eulixplatform-opstage/target/eulixplatform-opstage-*.jar -f $OSS_CI_EULIX_RES_BUCKET_DIR/eulixplatform-services/`head -1 VERSION`-alpha.$CI_PIPELINE_ID.jar
    - ossutil64 -i $OSS_CI_EULIX_RES_ACCESS_ID -k $OSS_CI_EULIX_RES_ACCESS_KEY -e $OSS_CI_EULIX_RES_ENDPOINT cp eulixplatform-common/target/eulixplatform-common-*.jar -f $OSS_CI_EULIX_RES_BUCKET_DIR/eulixplatform-common/`head -1 VERSION`-alpha.$CI_PIPELINE_ID.jar
    - ossutil64 -i $OSS_CI_EULIX_RES_ACCESS_ID -k $OSS_CI_EULIX_RES_ACCESS_KEY -e $OSS_CI_EULIX_RES_ENDPOINT cp eulixplatform-registry/target/eulixplatform-registry-*.jar -f $OSS_CI_EULIX_RES_BUCKET_DIR/eulixplatform-registry/`head -1 VERSION`-alpha.$CI_PIPELINE_ID.jar
  artifacts:
    paths:
      - eulixplatform-opstage/target/
      - eulixplatform-common/target/
      - eulixplatform-registry/target/
